/*
 * G-Code Viewer for きどりん for CNC
 * Embedded version — all IDs prefixed with gv to avoid conflicts
 * Based on TAB HEIGHT EXACT v12
 */
(function(){
'use strict';

const cv = document.getElementById('gv-cv');
if (!cv) return;
const ctx = cv.getContext('2d');
const DPR = window.devicePixelRatio || 1;

let gcLines=[], steps=[], curStep=0, playing=false, animId=null;
let matW=900, matH=900, matZ=13.5;
let cam={zoom:1,panX:0,panY:0,rotX:25,rotY:0,rotZ:0};
const camHome={zoom:1,panX:0,panY:0,rotX:25,rotY:0,rotZ:0};
let mouseMode='pan';

let detectedTabZ=null, detectedPass1Z=null, detectedFinalZ=null, detectedToolDiameter=null;
let detectedGcodeFormat='', detectedGcodeFormatDetail='';
let rawTabSegments=[], finalTabSegments=[], roughTabSegments=[];
let rawTabUpCount=0, rawTabDownCount=0;
let tabPass1Count=0, tabFinalCount=0, finalTabDepth=null;
const NUM_RE='[-+]?\\d*\\.?\\d+';

function escHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function normLine(raw){return String(raw||'').replace(/\u3000/g,' ');}
function commentsOf(raw){return (normLine(raw).match(/\([^)]*\)|（[^）]*）/g)||[]).join(' ');}
function codeOf(raw){return normLine(raw).replace(/\([^)]*\)|（[^）]*）/g,' ').replace(/;.*$/,' ').trim();}
function tabSearchText(raw){return normLine(raw);}
function hasTabUp(raw){return /\bTAB\s*UP\b/i.test(tabSearchText(raw));}
function hasTabDown(raw){return /\bTAB\s*DOWN\b/i.test(tabSearchText(raw));}
function axisVal(code,axis){const m=code.match(new RegExp(axis+'\\s*('+NUM_RE+')','i'));return m?parseFloat(m[1]):null;}
function hasRapidCmd(code){return /G0?0(?!\d)/i.test(code);}
function hasLinearCmd(code){return /G0?1(?!\d)/i.test(code);}
function fmtMM(v,d=1){return v!==null&&v!==undefined&&Number.isFinite(v)?Number(v).toFixed(d):'?';}
function getTabHeight(){return detectedTabZ!==null&&detectedFinalZ!==null?Math.abs(detectedFinalZ)-Math.abs(detectedTabZ):null;}
function isFinalTabStep(s){return !!s&&(s.inFinalTab||s.tabTransition||s.tabId!==null);}
function tabPhysicalKey(seg){const p1=`${seg.startX.toFixed(2)},${seg.startY.toFixed(2)}`;const p2=`${seg.endX.toFixed(2)},${seg.endY.toFixed(2)}`;return p1<p2?`${p1}|${p2}`:`${p2}|${p1}`;}
function uniquePhysicalTabCount(){const keys=new Set();for(const seg of finalTabSegments){if(seg.len>0.01)keys.add(tabPhysicalKey(seg));}return keys.size;}
function averageTabLength(){const lens=finalTabSegments.filter(t=>t.len>0.01).map(t=>t.len);return lens.length?lens.reduce((a,b)=>a+b,0)/lens.length:null;}

function nextLinearZAfterLine(lineIndex,maxLook=16){
  for(let j=lineIndex+1;j<Math.min(lineIndex+maxLook,gcLines.length);j++){
    const code=codeOf(gcLines[j]);const z=axisVal(code,'Z');
    if(z!==null&&hasLinearCmd(code))return {line:j,z};
  }
  return null;
}
function previousLinearCutZBeforeLine(lineIndex,maxLook=40){
  for(let j=lineIndex-1;j>=Math.max(0,lineIndex-maxLook);j--){
    const code=codeOf(gcLines[j]);const z=axisVal(code,'Z');
    if(z!==null&&hasLinearCmd(code)&&z<-0.5)return z;
  }
  return null;
}
function classifyPassDepth(z){
  if(z===null||z===undefined||!Number.isFinite(z))return 'unknown';
  if(finalTabDepth!==null&&Math.abs(z-finalTabDepth)<0.05)return 'final';
  if(detectedFinalZ!==null&&Math.abs(z-detectedFinalZ)<0.05)return 'final';
  if(detectedPass1Z!==null&&Math.abs(z-detectedPass1Z)<0.10)return 'pass1';
  return 'other';
}
function detectToolDiameter(){
  for(const l of gcLines){
    const c=commentsOf(l).replace(/[()（）]/g,' ').replace(/\s+/g,' ').trim();
    const m=c.match(/End\s*Mill\s*\{\s*([0-9]+(?:\.[0-9]+)?)\s*mm\s*\}/i)||c.match(/End\s*Mill[^0-9]*([0-9]+(?:\.[0-9]+)?)\s*mm/i)||c.match(/Tool[^0-9]*([0-9]+(?:\.[0-9]+)?)\s*mm/i);
    if(m)return parseFloat(m[1]);
  }
  return null;
}
function hasCode(code,g){return new RegExp(g+'(?!\\d)','i').test(code);}
function detectGcodeFormat(){
  let formatText='';
  for(const l of gcLines){
    const c=commentsOf(l).replace(/[()（）]/g,' ').replace(/\s+/g,' ').trim();
    if(/format/i.test(c)){const m=c.match(/-\s*([^()]*?format)\s*$/i);formatText=(m?m[1]:c).replace(/^Generated by\s*/i,'').trim();break;}
  }
  const allCode=gcLines.map(codeOf).join(' ').toUpperCase();
  const details=[];
  if(hasCode(allCode,'G21'))details.push('G21 mm'); else if(hasCode(allCode,'G20'))details.push('G20 inch');
  if(hasCode(allCode,'G90'))details.push('G90 absolute'); else if(hasCode(allCode,'G91'))details.push('G91 incremental');
  if(hasCode(allCode,'G17'))details.push('G17 XY'); else if(hasCode(allCode,'G18'))details.push('G18 ZX'); else if(hasCode(allCode,'G19'))details.push('G19 YZ');
  detectedGcodeFormatDetail=details.join(' / ');
  return formatText||detectedGcodeFormatDetail||'不明';
}
function detectRawTabSegments(){
  const segs=[];let cx=0,cy=0,cz=7,rapid=true,seg=null,tpx=0,tpy=0;
  for(let i=0;i<gcLines.length;i++){
    const raw=gcLines[i].trim();const code=codeOf(raw);const up=hasTabUp(raw),down=hasTabDown(raw);
    const xv=axisVal(code,'X'),yv=axisVal(code,'Y'),zv=axisVal(code,'Z');const hasMove=xv!==null||yv!==null||zv!==null;
    if(hasRapidCmd(code))rapid=true;if(hasLinearCmd(code))rapid=false;
    if(up){
      if(seg){seg.endLine=i-1;segs.push(seg);}
      seg={rawId:segs.length,startLine:i,endLine:i,startX:cx,startY:cy,startZ:cz,endX:cx,endY:cy,endZ:cz,len:0,moveLines:[],transitionLines:[],tabZ:null,downZ:null,passDepth:null,passClass:'unknown'};
      tpx=cx;tpy=cy;
    }
    const ox=cx,oy=cy,oz=cz;
    if(xv!==null)cx=xv;if(yv!==null)cy=yv;if(zv!==null)cz=zv;
    if(seg&&hasMove&&!rapid){
      const d=Math.hypot(cx-tpx,cy-tpy);
      if(d>0.001){seg.len+=d;seg.moveLines.push(i);}
      if(zv!==null&&Math.abs(cx-ox)<0.001&&Math.abs(cy-oy)<0.001)seg.transitionLines.push(i);
      if(seg.tabZ===null&&zv!==null)seg.tabZ=cz;
      tpx=cx;tpy=cy;seg.endX=cx;seg.endY=cy;seg.endZ=cz;
    }
    if(down&&seg){
      seg.endLine=i;const dm=nextLinearZAfterLine(i);
      if(dm){seg.downZ=dm.z;seg.transitionLines.push(dm.line);}
      if(seg.tabZ===null){const um=nextLinearZAfterLine(seg.startLine);if(um)seg.tabZ=um.z;}
      seg.passDepth=seg.downZ!==null?seg.downZ:previousLinearCutZBeforeLine(seg.startLine);
      segs.push(seg);seg=null;
    }
  }
  if(seg){seg.endLine=gcLines.length-1;seg.passDepth=previousLinearCutZBeforeLine(seg.startLine);segs.push(seg);}
  return segs;
}

function project3D(x3,y3,z3){
  const rx=cam.rotX*Math.PI/180,rz=cam.rotZ*Math.PI/180,ry=cam.rotY*Math.PI/180;
  let cx=x3-matW/2,cy=y3-matH/2,cz=z3,a,b;
  a=cx*Math.cos(rz)-cy*Math.sin(rz);b=cx*Math.sin(rz)+cy*Math.cos(rz);cx=a;cy=b;
  a=cy*Math.cos(rx)+cz*Math.sin(rx);b=cy*Math.sin(rx)-cz*Math.cos(rx);cy=a;cz=b;
  a=cx*Math.cos(ry)+cz*Math.sin(ry);cx=a;
  return{x:cx,y:cy};
}
function getTransform(){const r=cv.getBoundingClientRect(),pad=60;const s=Math.min((r.width-pad*2)/matW,(r.height-pad*2)/matH)*cam.zoom;return{scale:s,offX:r.width/2+cam.panX,offY:r.height/2+cam.panY};}
function toScreen(x3,y3,z3){const{scale:s,offX,offY}=getTransform(),p=project3D(x3,y3,z3||0);return{x:offX+p.x*s,y:offY-p.y*s};}
function toScreenTabLift(x3,y3,z3){return toScreen(x3,y3,z3);}

function parseGcode(){
  steps=[];rawTabSegments=[];finalTabSegments=[];roughTabSegments=[];detectedTabZ=null;detectedPass1Z=null;detectedFinalZ=null;detectedToolDiameter=null;detectedGcodeFormat='';detectedGcodeFormatDetail='';rawTabUpCount=0;rawTabDownCount=0;tabPass1Count=0;tabFinalCount=0;finalTabDepth=null;
  let cx=0,cy=0,cz=7,cf=2000,curRapid=true;
  for(const l of gcLines){
    const m=normLine(l).match(/X\s*=\s*([-+]?\d*\.?\d+).*Y\s*=\s*([-+]?\d*\.?\d+).*Z\s*=\s*([-+]?\d*\.?\d+)/i)||normLine(l).match(/X\s*=\s*([-+]?\d*\.?\d+).*Y\s*=\s*([-+]?\d*\.?\d+)/i);
    if(m){matW=parseFloat(m[1]);matH=parseFloat(m[2]);if(m[3]!==undefined)matZ=parseFloat(m[3]);}
  }
  rawTabUpCount=gcLines.filter(hasTabUp).length;rawTabDownCount=gcLines.filter(hasTabDown).length;
  detectedToolDiameter=detectToolDiameter();detectedGcodeFormat=detectGcodeFormat();

  const tabZset=new Set();
  for(let i=0;i<gcLines.length;i++){
    if(hasTabUp(gcLines[i])){
      for(let j=i+1;j<Math.min(i+10,gcLines.length);j++){const code=codeOf(gcLines[j]);const z=axisVal(code,'Z');if(z!==null&&hasLinearCmd(code)){tabZset.add(Number(z.toFixed(3)));break;}}
    }
  }
  detectedTabZ=tabZset.size?[...tabZset][0]:null;

  const zCounts={};
  for(const l of gcLines){const code=codeOf(l),z=axisVal(code,'Z');if(z!==null&&hasLinearCmd(code)&&z<-1){const k=z.toFixed(3);zCounts[k]=(zCounts[k]||0)+1;}}
  const zEntries=Object.entries(zCounts).map(([k,v])=>({z:parseFloat(k),count:v})).sort((a,b)=>a.z-b.z);
  detectedFinalZ=zEntries.length?zEntries[0].z:0;
  const cutZs=zEntries.filter(o=>detectedTabZ===null||Math.abs(o.z-detectedTabZ)>0.01).sort((a,b)=>a.z-b.z);
  detectedPass1Z=cutZs.length>=2?cutZs[cutZs.length-1].z:detectedFinalZ;

  rawTabSegments=detectRawTabSegments();
  const tabDepths=rawTabSegments.map(s=>s.passDepth).filter(v=>v!==null&&v!==undefined&&Number.isFinite(v));
  finalTabDepth=tabDepths.length?Math.min(...tabDepths):detectedFinalZ;
  for(const rs of rawTabSegments){
    if((rs.passDepth===null||rs.passDepth===undefined||!Number.isFinite(rs.passDepth))){rs.passDepth=previousLinearCutZBeforeLine(rs.startLine);}
    rs.passClass=classifyPassDepth(rs.passDepth);
    if(rs.passClass==='pass1')tabPass1Count++;else if(rs.passClass==='final')tabFinalCount++;
  }
  if(rawTabSegments.length>0&&tabFinalCount===0&&finalTabDepth!==null){
    for(const rs of rawTabSegments){
      if(rs.passDepth!==null&&Number.isFinite(rs.passDepth)&&Math.abs(rs.passDepth-finalTabDepth)<0.05){rs.passClass='final';tabFinalCount++;}
    }
  }

  cx=0;cy=0;cz=7;cf=2000;curRapid=true;
  for(let i=0;i<gcLines.length;i++){
    const raw=gcLines[i].trim();const code=codeOf(raw);const hasComment=commentsOf(raw).length>0;const rawTabUp=hasTabUp(raw),rawTabDown=hasTabDown(raw);
    const commentOnly=raw==='%'||((hasComment||rawTabUp||rawTabDown)&&(code===''||/^N\d+$/i.test(code)));
    if(commentOnly){
      steps.push({cmd:'comment',text:raw,code:'',x:cx,y:cy,z:cz,f:cf,lineNo:i,rapid:curRapid,comment:true,hasMove:false,rawTabUp,rawTabDown,inFinalTab:false,tabId:null,tabLen:null,tabHeight:null,tabTransition:false,tabTransDir:null,passClass:null});
      continue;
    }
    if(hasRapidCmd(code))curRapid=true;if(hasLinearCmd(code))curRapid=false;
    const xv=axisVal(code,'X'),yv=axisVal(code,'Y'),zv=axisVal(code,'Z'),fv=axisVal(code,'F');
    if(xv!==null)cx=xv;if(yv!==null)cy=yv;if(zv!==null)cz=zv;if(fv!==null)cf=fv;
    steps.push({cmd:raw,code,x:cx,y:cy,z:cz,f:cf,rapid:curRapid,comment:false,lineNo:i,hasMove:xv!==null||yv!==null||zv!==null,rawTabUp,rawTabDown,inFinalTab:false,tabId:null,tabLen:null,tabHeight:null,tabTransition:false,tabTransDir:null,passClass:null});
  }

  annotateFinalTabs();
  computeStepTimes();
  updateUIAfterParse();
  buildGcodeList();runEvaluation();resizeCanvas();drawFrame(0);updateGcodeList(0);
}

function annotateFinalTabs(){
  for(const s of steps){s.inFinalTab=false;s.tabId=null;s.tabLen=null;s.tabHeight=null;s.tabTransition=false;s.tabTransDir=null;s.passClass=null;}
  const lineToStep=new Map();for(let i=0;i<steps.length;i++)lineToStep.set(steps[i].lineNo,i);
  finalTabSegments=[];roughTabSegments=[];
  for(const rs of rawTabSegments){
    const si=lineToStep.has(rs.startLine)?lineToStep.get(rs.startLine):Math.max(0,Math.min(steps.length-1,rs.startLine));
    const ei=lineToStep.has(rs.endLine)?lineToStep.get(rs.endLine):Math.max(si,Math.min(steps.length-1,rs.endLine));
    const seg={id:null,startIndex:si,endIndex:ei,startX:rs.startX,startY:rs.startY,startZ:rs.startZ,endX:rs.endX,endY:rs.endY,endZ:rs.endZ,len:rs.len,indices:[],moveIndices:[],height:getTabHeight(),z:rs.tabZ!==null?rs.tabZ:detectedTabZ,source:'raw-comment',startLine:rs.startLine,endLine:rs.endLine,tabZ:rs.tabZ,downZ:rs.downZ,passDepth:rs.passDepth,passClass:rs.passClass};
    if(rs.passClass!=='final'){roughTabSegments.push(seg);continue;}
    seg.id=finalTabSegments.length;
    for(let i=si;i<=ei&&i<steps.length;i++){const s=steps[i];s.inFinalTab=true;s.tabId=seg.id;s.tabLen=rs.len;s.tabHeight=seg.height;s.passClass='final-tab';seg.indices.push(i);if(s.hasMove&&!s.comment)seg.moveIndices.push(i);}
    finalTabSegments.push(seg);
  }
  markFinalTabZTransitions();
}
function markFinalTabZTransitions(){
  for(const seg of finalTabSegments){
    for(const commentIndex of [seg.startIndex,seg.endIndex]){
      const c=steps[commentIndex];if(!c)continue;
      const dir=c.rawTabUp?'up':(c.rawTabDown?'down':null);if(!dir)continue;
      for(let j=commentIndex+1;j<Math.min(commentIndex+8,steps.length);j++){
        const s=steps[j];if(!s)break;if(s.comment)continue;if(!s.hasMove)continue;
        const hasZ=axisVal(s.code||'','Z')!==null;
        if(hasZ&&!s.rapid){s.inFinalTab=true;s.tabTransition=true;s.tabTransDir=dir;s.tabId=seg.id;s.tabLen=seg.len;s.tabHeight=seg.height;s.passClass='final-tab';}
        break;
      }
    }
  }
}
function updateUIAfterParse(){
  document.getElementById('gvStatW').textContent=fmtMM(matW);
  document.getElementById('gvStatH').textContent=fmtMM(matH);
  document.getElementById('gvStatZ').textContent=fmtMM(matZ);
  document.getElementById('gvStatLines').textContent=steps.length;
  document.getElementById('gvStatToolDia').textContent=detectedToolDiameter!==null?`${fmtMM(detectedToolDiameter)}mm`:'—';
  document.getElementById('gvStatGFormat').textContent=detectedGcodeFormat||'—';
  document.getElementById('gvStatGFormat').title=detectedGcodeFormatDetail||detectedGcodeFormat||'';
  document.getElementById('gvStatPass').textContent=`${fmtMM(detectedPass1Z,3)} / ${fmtMM(detectedFinalZ,3)}`;
  document.getElementById('gvStatTabCount').textContent=`${uniquePhysicalTabCount()}個`;
  const avg=averageTabLength(),h=getTabHeight();
  document.getElementById('gvStatTabSize').textContent=(avg!==null&&h!==null)?`${fmtMM(avg)}×${fmtMM(h)}mm`:'—';
  document.getElementById('gvStatTabRaw').textContent=`${rawTabUpCount}/${rawTabDownCount}`;
  const legend=document.getElementById('gvLegendTabText');if(legend)legend.textContent=(avg!==null&&h!==null)?`実タブ(${fmtMM(avg)}mm×${fmtMM(h)}mm)`:'タブ';
  ['gvMatSection','gvCodeInfoSection','gvPlaySection','gvSliderSection'].forEach(id=>document.getElementById(id).style.display='');
  const sl=document.getElementById('gvStepSlider');sl.max=Math.max(0,steps.length-1);sl.value=0;curStep=0;sl.style.setProperty('--pct','0%');
  document.getElementById('gvStepDisplay').textContent=`0 / ${Math.max(0,steps.length-1)}`;
  // 時間表示初期化
  simElapsed = 0; lastAnimTimestamp = 0;
  const timeEl = document.getElementById('gvTimeDisplay');
  if(timeEl) timeEl.textContent = `加工時間: ${fmtTime(0)} / ${fmtTime(totalMachiningTime)}`;
  Object.assign(cam,{...camHome});
}

function buildGcodeList(){
  const c=document.getElementById('gvGcodeList');c.innerHTML='';
  steps.forEach((s,i)=>{const d=document.createElement('div');let cls='gv-gc-line';if(isFinalTabStep(s))cls+=' is-tab';else if(s.comment)cls+=' is-comment';else if(s.hasMove)cls+=' is-move';d.className=cls;d.innerHTML=`<span class="gv-gc-num">${i}</span><span class="gv-gc-cmd">${escHtml(s.comment?s.text:s.cmd)}</span>`;c.appendChild(d);});
}
function updateGcodeList(step){
  const c=document.getElementById('gvGcodeList'),items=c.children;const old=c.querySelector('.active');if(old)old.classList.remove('active');
  if(step<items.length){const el=items[step];el.classList.add('active','executed');const cR=c.getBoundingClientRect(),eR=el.getBoundingClientRect();if(eR.top<cR.top||eR.bottom>cR.bottom)el.scrollIntoView({block:'center'});}
  for(let i=0;i<=step&&i<items.length;i++)items[i].classList.add('executed');
}

function resizeCanvas(){
  const overlay = document.getElementById('gcode-viewer-overlay');
  if (!overlay || overlay.style.display === 'none') return;
  const r=cv.parentElement.getBoundingClientRect();
  cv.width=r.width*DPR;cv.height=r.height*DPR;
  cv.style.width=r.width+'px';cv.style.height=r.height+'px';
  ctx.setTransform(DPR,0,0,DPR,0,0);
}
window.addEventListener('resize',()=>{
  const overlay = document.getElementById('gcode-viewer-overlay');
  if (overlay && overlay.style.display !== 'none'){resizeCanvas();drawFrame(curStep);}
});

function pathDepthClass(z){
  if(detectedFinalZ!==null&&Math.abs(z-detectedFinalZ)<0.08)return 'final';
  if(detectedPass1Z!==null&&Math.abs(z-detectedPass1Z)<0.12)return 'pass1';
  if(detectedTabZ!==null&&Math.abs(z-detectedTabZ)<0.08)return 'tabz';
  return 'other';
}
function collectSegments(upTo){
  const segs=[];let px=0,py=0,pz=7;
  for(let i=0;i<=upTo&&i<steps.length;i++){
    const s=steps[i];if(s.comment){continue;}
    if(!s.hasMove){px=s.x;py=s.y;pz=s.z;continue;}
    const movedXY=Math.abs(s.x-px)>0.001||Math.abs(s.y-py)>0.001;
    const movedZ=Math.abs(s.z-pz)>0.001;
    if(movedXY||movedZ){
      const zLayer=Math.min(pz,s.z);
      segs.push({index:i,x1:px,y1:py,z1:pz,x2:s.x,y2:s.y,z2:s.z,rapid:s.rapid,tab:isFinalTabStep(s)&&!s.rapid&&(s.z<-0.5||pz<-0.5),movedXY,movedZ,zLayer,depth:pathDepthClass(zLayer),step:s});
    }
    px=s.x;py=s.y;pz=s.z;
  }
  return segs;
}
function drawPathSegment(seg){
  const screenFn=seg.tab?toScreenTabLift:toScreen;
  const from=screenFn(seg.x1,seg.y1,Math.min(seg.z1,0)),to=screenFn(seg.x2,seg.y2,Math.min(seg.z2,0));
  if(seg.tab){
    const zOnly=!seg.movedXY&&seg.movedZ;ctx.lineCap=zOnly?'square':'round';ctx.setLineDash([]);
    ctx.strokeStyle='rgba(255,215,0,0.34)';ctx.lineWidth=zOnly?6:7;ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();
    ctx.strokeStyle='#ffd700';ctx.lineWidth=zOnly?2.5:3;ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();ctx.lineCap='butt';
  }else if(seg.rapid){
    ctx.strokeStyle='rgba(0,210,255,.10)';ctx.lineWidth=.5;ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();ctx.setLineDash([]);
  }else if(seg.z2<-0.5||seg.z1<-0.5){
    const r=Math.min(Math.abs(seg.zLayer)/Math.max(matZ,1),1);
    if(seg.depth==='final'){ctx.strokeStyle=`rgba(150,38,28,${0.55+0.35*r})`;ctx.lineWidth=1.1+r*0.5;}
    else if(seg.depth==='pass1'){ctx.strokeStyle=`rgba(255,120,62,${0.60+0.25*r})`;ctx.lineWidth=1.25+r*0.4;}
    else {ctx.strokeStyle=`rgba(255,90,45,${0.45+0.35*r})`;ctx.lineWidth=1.0+r*0.4;}
    ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();
  }else{
    ctx.strokeStyle='rgba(0,210,255,.06)';ctx.lineWidth=.4;ctx.setLineDash([2,2]);ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();ctx.setLineDash([]);
  }
}
function drawFrame(upTo){
  const W=cv.width/DPR,H=cv.height/DPR;ctx.clearRect(0,0,W,H);
  const c3=[[0,0,0],[matW,0,0],[matW,matH,0],[0,matH,0],[0,0,-matZ],[matW,0,-matZ],[matW,matH,-matZ],[0,matH,-matZ]].map(c=>toScreen(c[0],c[1],c[2]));
  ctx.strokeStyle='#c4a35a33';ctx.lineWidth=1;ctx.setLineDash([5,4]);ctx.beginPath();ctx.moveTo(c3[4].x,c3[4].y);for(let i=5;i<=7;i++)ctx.lineTo(c3[i].x,c3[i].y);ctx.closePath();ctx.stroke();ctx.setLineDash([]);
  ctx.fillStyle='#c4a35a18';ctx.strokeStyle='#c4a35a55';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(c3[0].x,c3[0].y);for(let i=1;i<=3;i++)ctx.lineTo(c3[i].x,c3[i].y);ctx.closePath();ctx.fill();ctx.stroke();
  ctx.strokeStyle='#c4a35a30';ctx.lineWidth=.5;for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(c3[i].x,c3[i].y);ctx.lineTo(c3[i+4].x,c3[i+4].y);ctx.stroke();}
  ctx.strokeStyle='#ffffff06';ctx.lineWidth=.5;for(let gx=0;gx<=matW;gx+=100){const a=toScreen(gx,0,0),b=toScreen(gx,matH,0);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}for(let gy=0;gy<=matH;gy+=100){const a=toScreen(0,gy,0),b=toScreen(matW,gy,0);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
  const o=toScreen(0,0,0);ctx.strokeStyle='#ff000066';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(o.x-7,o.y);ctx.lineTo(o.x+7,o.y);ctx.stroke();ctx.beginPath();ctx.moveTo(o.x,o.y-7);ctx.lineTo(o.x,o.y+7);ctx.stroke();

  const segs=collectSegments(upTo);
  const rapid=segs.filter(s=>s.rapid);
  const normal=segs.filter(s=>!s.rapid&&!s.tab);
  const tab=segs.filter(s=>s.tab);
  rapid.forEach(drawPathSegment);
  normal.sort((a,b)=>a.zLayer-b.zLayer||a.index-b.index).forEach(drawPathSegment);
  tab.sort((a,b)=>a.zLayer-b.zLayer||a.index-b.index).forEach(drawPathSegment);

  drawTabHeightMarkers(upTo);
  drawTool(upTo,W,H);
}
function drawTabHeightMarkers(upTo){
  if(detectedTabZ===null||detectedFinalZ===null||!finalTabSegments.length)return;
  ctx.save();
  for(const seg of finalTabSegments){
    if(seg.endIndex>upTo||seg.len<=0.01)continue;
    const mx=(seg.startX+seg.endX)/2,my=(seg.startY+seg.endY)/2;
    const top=toScreenTabLift(mx,my,detectedTabZ),bottom=toScreenTabLift(mx,my,detectedFinalZ);
    ctx.strokeStyle='rgba(255,215,0,.55)';ctx.lineWidth=1.25;ctx.setLineDash([2,2]);ctx.beginPath();ctx.moveTo(bottom.x,bottom.y);ctx.lineTo(top.x,top.y);ctx.stroke();ctx.setLineDash([]);
    ctx.fillStyle='rgba(255,215,0,.9)';ctx.beginPath();ctx.arc(top.x,top.y,2.2,0,Math.PI*2);ctx.fill();
  }
  ctx.restore();
}
function drawTool(upTo,W,H){
  if(upTo>=0&&upTo<steps.length){
    const s=steps[upTo],tp=(isFinalTabStep(s)?toScreenTabLift:toScreen)(s.x,s.y,Math.min(s.z,0)),{scale}=getTransform(),tr=3*scale;
    ctx.strokeStyle=isFinalTabStep(s)?'#ffd700':s.z<-0.5?'#ff3366':'#00d2ff';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(tp.x,tp.y,tr,0,Math.PI*2);ctx.stroke();
    ctx.strokeStyle='#ffffff66';ctx.lineWidth=.5;ctx.beginPath();ctx.moveTo(tp.x-10,tp.y);ctx.lineTo(tp.x+10,tp.y);ctx.stroke();ctx.beginPath();ctx.moveTo(tp.x,tp.y-10);ctx.lineTo(tp.x,tp.y+10);ctx.stroke();
    ctx.font='10px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace';ctx.fillStyle='#ffffffaa';ctx.fillText(`X${s.x.toFixed(1)} Y${s.y.toFixed(1)} Z${s.z.toFixed(1)}`,tp.x+12,tp.y-6);
    if(isFinalTabStep(s)){ctx.fillStyle='#ffd700';ctx.font='bold 11px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace';ctx.fillText(`■ 実TAB${s.tabTransition?' Z-'+(s.tabTransDir==='down'?'DOWN':'UP'):''} 幅${fmtMM(s.tabLen)}mm 高さ${fmtMM(s.tabHeight)}mm`,tp.x+12,tp.y+10);}
  }
  // 軸インジケーター非表示
  if(steps.length>0&&upTo>=0&&upTo<steps.length){const s=steps[upTo];const tabInfo=isFinalTabStep(s)?` [実TAB${s.tabTransition?' Z-'+(s.tabTransDir==='down'?'DOWN':'UP'):''} 幅${fmtMM(s.tabLen)}mm 高さ${fmtMM(s.tabHeight)}mm]`:'';const elapsed=upTo>0&&upTo<stepCumTime.length?stepCumTime[upTo]:0;document.getElementById('gvInfoBox').textContent=`Step ${upTo}/${steps.length-1}  X${s.x.toFixed(1)} Y${s.y.toFixed(1)} Z${s.z.toFixed(1)}  ${fmtTime(elapsed)}/${fmtTime(totalMachiningTime)}${tabInfo}`;}else document.getElementById('gvInfoBox').textContent='G-Codeを読み込んでください';
}

// Mouse / touch interaction
let dragging=false,lastMX=0,lastMY=0;
cv.addEventListener('mousedown',e=>{dragging=true;lastMX=e.clientX;lastMY=e.clientY;cv.classList.add(mouseMode==='rotate'?'rotating':'dragging');});
window.addEventListener('mouseup',()=>{dragging=false;cv.classList.remove('dragging','rotating');});
cv.addEventListener('mousemove',e=>{if(!dragging)return;const dx=e.clientX-lastMX,dy=e.clientY-lastMY;lastMX=e.clientX;lastMY=e.clientY;if(mouseMode==='pan'){cam.panX+=dx;cam.panY+=dy;}else{cam.rotZ+=dx*.4;cam.rotX-=dy*.4;cam.rotX=Math.max(-90,Math.min(90,cam.rotX));}drawFrame(curStep);});
cv.addEventListener('wheel',e=>{e.preventDefault();cam.zoom*=e.deltaY<0?1.1:.9;cam.zoom=Math.max(.1,Math.min(20,cam.zoom));drawFrame(curStep);},{passive:false});

document.getElementById('gvTbZoomIn').addEventListener('click',()=>{cam.zoom=Math.min(20,cam.zoom*1.25);drawFrame(curStep);});
document.getElementById('gvTbZoomOut').addEventListener('click',()=>{cam.zoom=Math.max(.1,cam.zoom*.8);drawFrame(curStep);});
document.getElementById('gvTbPan').addEventListener('click',()=>{mouseMode='pan';document.getElementById('gvTbPan').classList.add('active');document.getElementById('gvTbRotate').classList.remove('active');});
document.getElementById('gvTbRotate').addEventListener('click',()=>{mouseMode='rotate';document.getElementById('gvTbRotate').classList.add('active');document.getElementById('gvTbPan').classList.remove('active');});
document.getElementById('gvTbHome').addEventListener('click',()=>{Object.assign(cam,{...camHome});drawFrame(curStep);});
document.getElementById('gvStepSlider').addEventListener('input',function(){
  if(playing)stopPlay();
  curStep=parseInt(this.value)||0;
  // スライダー操作時にsimElapsedも同期
  simElapsed = curStep < stepCumTime.length ? (curStep > 0 ? stepCumTime[curStep-1] : 0) : 0;
  updateSliderUI();
  drawFrame(curStep);updateGcodeList(curStep);
});
document.getElementById('gvBtnPlay').addEventListener('click',()=>{playing?stopPlay():startPlay();});
document.getElementById('gvBtnReset').addEventListener('click',()=>{
  stopPlay();curStep=0;simElapsed=0;lastAnimTimestamp=0;
  updateSliderUI();
  drawFrame(0);
  document.querySelectorAll('.gv-gc-line.executed').forEach(el=>el.classList.remove('executed'));
  updateGcodeList(0);
});

// ===== 時間ベースアニメーション =====
const RAPID_SPEED = 5000; // G0早送り速度 mm/min
let stepCumTime = [];      // 各ステップ終了時の累計時間(分)
let totalMachiningTime = 0; // 総加工時間(分)
let simElapsed = 0;         // シミュレーション経過時間(分)
let lastAnimTimestamp = 0;  // 前フレームのtimestamp

function computeStepTimes(){
  stepCumTime = new Array(steps.length);
  let cumTime = 0;
  let prevX = 0, prevY = 0, prevZ = 7;
  for(let i = 0; i < steps.length; i++){
    const s = steps[i];
    if(!s.comment && s.hasMove){
      const dist = Math.sqrt((s.x-prevX)**2 + (s.y-prevY)**2 + (s.z-prevZ)**2);
      const feed = s.rapid ? RAPID_SPEED : (s.f || 2000);
      s.dist = dist;
      s.duration = feed > 0 ? dist / feed : 0; // 分
      prevX = s.x; prevY = s.y; prevZ = s.z;
    } else {
      s.dist = 0;
      s.duration = 0;
    }
    cumTime += s.duration;
    stepCumTime[i] = cumTime;
  }
  totalMachiningTime = cumTime;
}

function findStepAtTime(t){
  if(t <= 0) return 0;
  if(t >= totalMachiningTime) return steps.length - 1;
  let lo = 0, hi = steps.length - 1;
  while(lo < hi){
    const mid = (lo + hi) >> 1;
    if(stepCumTime[mid] < t) lo = mid + 1;
    else hi = mid;
  }
  return lo;
}

function fmtTime(minutes){
  const totalSec = Math.round(minutes * 60);
  const h = Math.floor(totalSec / 3600);
  const m = Math.floor((totalSec % 3600) / 60);
  const s = totalSec % 60;
  if(h > 0) return `${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;
  return `${m}:${String(s).padStart(2,'0')}`;
}

function updateSliderUI(){
  const sl = document.getElementById('gvStepSlider');
  sl.value = curStep;
  sl.style.setProperty('--pct', (curStep / Math.max(1, steps.length-1) * 100) + '%');
  document.getElementById('gvStepDisplay').textContent = `${curStep} / ${Math.max(0, steps.length-1)}`;
  const timeEl = document.getElementById('gvTimeDisplay');
  if(timeEl){
    const elapsed = curStep > 0 && curStep <= stepCumTime.length ? stepCumTime[Math.min(curStep, stepCumTime.length-1)] : 0;
    timeEl.textContent = `加工時間: ${fmtTime(elapsed)} / ${fmtTime(totalMachiningTime)}`;
  }
}

function startPlay(){
  if(!steps.length) return;
  if(curStep >= steps.length - 1){ curStep = 0; simElapsed = 0; }
  // 現在のステップから再開するためsimElapsedを同期
  if(simElapsed <= 0 && curStep > 0){
    simElapsed = stepCumTime[curStep - 1] || 0;
  }
  playing = true;
  lastAnimTimestamp = 0;
  document.getElementById('gvBtnPlay').textContent = '⏸ 一時停止';
  animId = requestAnimationFrame(animateTimeBase);
}
function stopPlay(){
  playing = false;
  lastAnimTimestamp = 0;
  document.getElementById('gvBtnPlay').textContent = '▶ 再開';
  if(animId) cancelAnimationFrame(animId);
}

function animateTimeBase(timestamp){
  if(!playing) return;
  if(!lastAnimTimestamp) lastAnimTimestamp = timestamp;

  const deltaMs = Math.min(timestamp - lastAnimTimestamp, 200); // 最大200msキャップ
  lastAnimTimestamp = timestamp;

  const speedMul = parseFloat(document.getElementById('gvSpeedSel').value) || 10;
  simElapsed += (deltaMs / 1000 / 60) * speedMul; // 実時間→シミュレーション分

  if(simElapsed >= totalMachiningTime){
    curStep = steps.length - 1;
    simElapsed = totalMachiningTime;
    updateSliderUI();
    drawFrame(curStep); updateGcodeList(curStep);
    stopPlay();
    document.getElementById('gvBtnPlay').textContent = '▶ 開始';
    return;
  }

  const newStep = findStepAtTime(simElapsed);
  if(newStep !== curStep){
    curStep = newStep;
    updateSliderUI();
    drawFrame(curStep); updateGcodeList(curStep);
  }

  if(playing) animId = requestAnimationFrame(animateTimeBase);
}

function runEvaluation(){
  const rpt=document.getElementById('gvReportArea'),L=[];
  const add=(c,l,v)=>L.push(`<div class="gv-rpt-row"><span class="gv-rpt-label">${l}</span><span class="${c?'gv-'+c:''}">${v}</span></div>`);
  const tabH=getTabHeight(),avg=averageTabLength(),tabLens=finalTabSegments.filter(t=>t.len>0.01).map(t=>t.len);
  const expectedTabWidth=(detectedToolDiameter!==null&&detectedToolDiameter>=10)?20:16;
  const tabWidthTol=2.1;
  const tabOK=tabLens.filter(t=>Math.abs(t-expectedTabWidth)<=tabWidthTol),tabNG=tabLens.filter(t=>Math.abs(t-expectedTabWidth)>tabWidthTol);
  const zMoveCount=steps.filter(s=>s.tabTransition).length;
  const feeds=new Set();for(const s of steps)if(s.f&&!s.comment)feeds.add(s.f);
  let xMin=Infinity,xMax=-Infinity,yMin=Infinity,yMax=-Infinity;for(const s of steps)if(!s.comment&&s.hasMove&&s.z<-1){xMin=Math.min(xMin,s.x);xMax=Math.max(xMax,s.x);yMin=Math.min(yMin,s.y);yMax=Math.max(yMax,s.y);}
  const hasM30=gcLines.some(l=>/M30/i.test(l)),hasPct=gcLines.length>1&&gcLines[0].trim()==='%'&&gcLines[gcLines.length-1].trim()==='%';
  let prevN=null,gaps=0;for(const l of gcLines){const m=l.match(/^N(\d+)/i);if(m){const n=parseInt(m[1],10);if(prevN!==null&&n!==prevN+10)gaps++;prevN=n;}}
  L.push('<div class="gv-rpt-title">■ G-Code評価レポート（TAB HEIGHT EXACT v12）</div>');
  add(rawTabUpCount===rawTabDownCount&&rawTabUpCount>0?'rpt-ok':'rpt-warn','TABコメント検出',`TAB UP ${rawTabUpCount} / TAB DOWN ${rawTabDownCount} / ペア ${rawTabSegments.length}`);
  add(finalTabSegments.length>0?'rpt-ok':'rpt-ng','実タブ検出',`${uniquePhysicalTabCount()}個（最終周回の黄色表示対象 ${finalTabSegments.length}区間）`);
  add('rpt-ok','TAB周回内訳',`浅い周回コメント ${tabPass1Count}区間 / 最終周回実タブ ${tabFinalCount}区間`);
  add(finalTabDepth!==null?'rpt-ok':'rpt-warn','実タブ判定深さ',finalTabDepth!==null?`TAB DOWN後の最深戻りZ ${fmtMM(finalTabDepth,3)}`:'—');
  add(detectedPass1Z!==null&&detectedFinalZ!==null?'rpt-ok':'rpt-warn','周回深さ',(detectedPass1Z!==null&&detectedFinalZ!==null&&Math.abs(detectedPass1Z-detectedFinalZ)<0.05)?`単周 Z${fmtMM(detectedFinalZ,3)}`:`浅い周回 Z${fmtMM(detectedPass1Z,3)} / 最終周回 Z${fmtMM(detectedFinalZ,3)}`);
  add(detectedTabZ!==null?'rpt-ok':'rpt-warn','タブZ値',detectedTabZ!==null?`Z${fmtMM(detectedTabZ,3)}`:'検出なし');
  add(tabH!==null&&Math.abs(tabH-6)<0.5?'rpt-ok':'rpt-warn','タブ高さ',tabH!==null?`${tabH.toFixed(1)}mm ${Math.abs(tabH-6)<0.5?'✅':'⚠️'}`:'—');
  if(tabLens.length){add(tabNG.length===0?'rpt-ok':'rpt-warn','タブ幅',`平均 ${avg.toFixed(1)}mm / 基準${expectedTabWidth.toFixed(0)}±2mm: ${tabOK.length}/${tabLens.length} / 異常: ${tabNG.length}`);}
  add(zMoveCount===finalTabSegments.length*2?'rpt-ok':'rpt-warn','タブZ移動描画',`最終周回のTAB UP/DOWNに伴うZ移動 ${zMoveCount}本を黄色表示`);
  add(detectedToolDiameter!==null?'rpt-ok':'rpt-warn','エンドミル直径',detectedToolDiameter!==null?`${fmtMM(detectedToolDiameter)}mm`:'検出なし');
  add(detectedGcodeFormat?'rpt-ok':'rpt-warn','G-code Format',`${detectedGcodeFormat}${detectedGcodeFormatDetail?' / '+detectedGcodeFormatDetail:''}`);
  add('rpt-ok','Z表示方向','通常切削はZマイナス方向を画面下側へ投影（深い周回は浅い周回より下）');
  add('rpt-ok','TAB高さ表示','黄色TABも通常切削と同じZ投影を使用（拡大補正なし、6.0mmを実寸反映）');
  add('rpt-ok','重ね描画順','深いZを先に描画し、浅い周回を後から描画（深い周回が上塗りされない）');
  if(xMin<Infinity){const oob=xMin<-1||yMin<-1||xMax>matW+1||yMax>matH+1;add('','切削範囲 X',`${xMin.toFixed(1)} ～ ${xMax.toFixed(1)}mm`);add('','切削範囲 Y',`${yMin.toFixed(1)} ～ ${yMax.toFixed(1)}mm`);add(oob?'rpt-ng':'rpt-ok','材料範囲内',oob?'❌ はみ出しあり':'✅ 全座標が材料内');}
  add(hasM30?'rpt-ok':'rpt-ng','M30（終了命令）',hasM30?'✅ あり':'❌ なし');
  add(hasPct?'rpt-ok':'rpt-warn','%マーカー',hasPct?'✅ 先頭/末尾':'⚠️');
  add(gaps===0?'rpt-ok':'rpt-warn','行番号連続性',gaps===0?'✅ 連続':`⚠️ ${gaps}件ギャップ`);
  add('','送り速度',`${[...feeds].sort((a,b)=>a-b).join(', ')} mm/min`);
  add('rpt-ok','推定加工時間',`${fmtTime(totalMachiningTime)}（早送り${RAPID_SPEED} mm/min 想定）`);
  const issues=[];if(finalTabSegments.length===0)issues.push('実タブなし');if(tabNG.length)issues.push(`異常タブ${tabNG.length}区間`);if(!hasM30)issues.push('M30なし');if(xMin<-1||yMin<-1||xMax>matW+1||yMax>matH+1)issues.push('座標はみ出し');
  L.push('<div style="margin-top:6px;padding-top:6px;border-top:1px solid #2a2a4a">');
  L.push(issues.length===0?'<div class="gv-rpt-row"><span class="gv-rpt-label" style="font-weight:700">総合判定</span><span class="gv-rpt-ok" style="font-weight:700;font-size:14px">✅ 合格 — タブ検出とZ表示を確認済み</span></div>':`<div class="gv-rpt-row"><span class="gv-rpt-label" style="font-weight:700">総合判定</span><span class="gv-rpt-ng" style="font-weight:700">⚠️ ${issues.join('、')}</span></div>`);
  L.push('</div>');rpt.innerHTML=L.join('');
}

// ビュワー終了ボタン
document.getElementById('gv-close-button').addEventListener('click',()=>{
  stopPlay();
  document.getElementById('gcode-viewer-overlay').style.display='none';
});

// 厚さモーダルのOKボタン（外部ファイル読み込み時用 — 通常は不使用）
document.getElementById('gvThickOk').addEventListener('click',()=>{
  matZ=parseFloat(document.getElementById('gvThickInput').value)||13.5;
  document.getElementById('gvThickModal').classList.remove('show');
  parseGcode();
});

// 公開API：きどりん本体から呼び出される
// 内部ロード関数（セレクター表示を操作しない）
function _loadGcodeInternal(gcodeText, matThick){
  matZ = matThick || 13.5;
  gcLines = gcodeText.split(/\r?\n/).filter(l=>l.trim());
  setTimeout(()=>{
    parseGcode();
  }, 50);
}

window.gvOpenWithGcode = function(gcodeText, matThick){
  // 単体呼び出し時はセレクターを非表示
  const sel = document.getElementById('gvBoardSelector');
  if (sel) sel.style.display = 'none';
  _loadGcodeInternal(gcodeText, matThick);
};

// Gコード未生成でもビュワーを開く（空状態表示）
window.gvOpenEmpty = function(){
  const sel = document.getElementById('gvBoardSelector');
  if (sel) sel.style.display = 'none';
  stopPlay();
  gcLines = []; steps = []; curStep = 0;
  resizeCanvas();
  drawFrame(0);
  document.getElementById('gvInfoBox').textContent = 'G-Codeを読み込んでください';
  const rpt = document.getElementById('gvReportArea');
  if (rpt) rpt.innerHTML = '<div class="gv-rpt-title">▶ G-Codeを読み込むと評価レポートが表示されます</div>';
};

// 複数板対応API
let multiGcodeData = null;
window.gvOpenWithMultiGcode = function(gcodes){
  multiGcodeData = gcodes;
  const selWrap = document.getElementById('gvBoardSelector');
  const selEl = document.getElementById('gvBoardSelect');
  if (!selWrap || !selEl) {
    if (gcodes.length > 0) _loadGcodeInternal(gcodes[0].gcode, gcodes[0].matThick);
    return;
  }
  if (gcodes.length <= 1) {
    selWrap.style.display = 'none';
    if (gcodes.length === 1) _loadGcodeInternal(gcodes[0].gcode, gcodes[0].matThick);
    return;
  }
  // 板セレクター表示
  selWrap.style.display = '';
  selEl.innerHTML = '';
  gcodes.forEach((g, i) => {
    const opt = document.createElement('option');
    opt.value = String(i);
    opt.textContent = `${g.label}（${g.boardLength}\u00D7${g.boardWidth}mm / 部品${g.partCount}）`;
    selEl.appendChild(opt);
  });
  selEl.value = '0';
  // 1枚目を表示（セレクターは隠さない）
  _loadGcodeInternal(gcodes[0].gcode, gcodes[0].matThick);
};

// 板セレクター変更イベント
const gvBoardSelectEl = document.getElementById('gvBoardSelect');
if (gvBoardSelectEl) {
  gvBoardSelectEl.addEventListener('change', function(){
    if (!multiGcodeData) return;
    const idx = parseInt(this.value) || 0;
    if (idx >= 0 && idx < multiGcodeData.length) {
      stopPlay();
      curStep = 0;
      _loadGcodeInternal(multiGcodeData[idx].gcode, multiGcodeData[idx].matThick);
    }
  });
}

// 「G-codeファイル読み込み」ボタン：別のGコードファイルを開く
const gvLoadFileBtn = document.getElementById('gvLoadFileBtn');
const gvFileInput = document.getElementById('gvFileInput');
if (gvLoadFileBtn && gvFileInput) {
  gvLoadFileBtn.addEventListener('click', () => gvFileInput.click());
  gvFileInput.addEventListener('change', function(){
    const file = this.files && this.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = function(e){
      stopPlay();
      multiGcodeData = null;
      const sel = document.getElementById('gvBoardSelector');
      if (sel) sel.style.display = 'none';
      curStep = 0;
      _loadGcodeInternal(e.target.result, matZ || 13.5);
    };
    reader.onerror = function(){
      alert('ファイルの読み込みに失敗しました。');
    };
    reader.readAsText(file);
    // 同じファイルを連続で選択できるようリセット
    gvFileInput.value = '';
  });
}

})();
